#version 450

#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_shader_image_load_formatted : require

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform image2D result_image;
layout(set = 0, binding = 1) uniform TestInput {
    float b;
    uint c;
    mat4 d;
    vec2 e;
    ivec2 h;
    uvec2 k;
    bool n;
}
test_input;

void main() {
    ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
    vec4 color         = vec4(0.0, 0.0, 0.0, 1.0);
    color.r            = test_input.b;
    imageStore(result_image, pixel_coords, color);
}
