// ============================================================================
// !!! DO NOT EDIT THIS FILE BY HAND !!!
// Generated by build.rs::generate_gpu_structs from GLSL shader sources.
// ============================================================================

#![allow(dead_code, non_snake_case)]

/// Auto-generated from `B_BvhNodes` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct BvhNodes {
    pub aabb_min: [f32; 3],
    pub _pad0: [u8; 4],
    pub aabb_max: [f32; 3],
    pub offset: u32,
}

/// Auto-generated from `B_ChunkSolidSamples` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct ChunkSolidSamples {
    pub solid: [u32; 0],
}

/// Auto-generated from `B_CounterForLevels` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct CounterForLevels {
    pub data: [u32; 0],
}

/// Auto-generated from `B_Cuboids` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct Cuboids {
    pub min_corner: [f32; 3],
    pub _pad0: f32,
    pub max_corner: [f32; 3],
    pub _pad1: f32,
}

/// Auto-generated from `B_EditRemovalCandidates` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct EditRemovalCandidates {
    pub positions: [u32; 0],
}

/// Auto-generated from `B_EditRemovalSample` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct EditRemovalSample {
    pub sample_count: u32,
    pub _pad0: [u8; 12],
    pub positions: [u32; 200],
}

/// Auto-generated from `B_EditStats` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct EditStats {
    pub removed_counts: [u32; 8],
    pub added_counts: [u32; 8],
}

/// Auto-generated from `B_FloraVoxelInfos` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct FloraVoxelInfos {
    pub entries: [u32; 0],
}

/// Auto-generated from `B_FloraVoxelTableDescs` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct FloraVoxelTableDescs {
    pub descs: [u32; 28],
}

/// Auto-generated from `B_GrassGrowthPotentialLevels` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct GrassGrowthPotentialLevels {
    pub words: [u32; 0],
}

/// Auto-generated from `B_LevelDispatchIndirect` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct LevelDispatchIndirect {
    pub dispatch_x: u32,
    pub dispatch_y: u32,
    pub dispatch_z: u32,
}

/// Auto-generated from `B_MakeSurfaceResult` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct MakeSurfaceResult {
    pub active_voxel_len: u32,
    pub active_brick_len: u32,
}

/// Auto-generated from `B_ManualFloraInstances` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct ManualFloraInstances {
    pub packed_local_pos: u32,
    pub spawn_start_ms: u32,
}

/// Auto-generated from `B_ModelTriangles` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct ModelTriangles {
    pub data: [u32; 0],
}

/// Auto-generated from `B_NodeOffsetForLevels` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct NodeOffsetForLevels {
    pub data: [u32; 0],
}

/// Auto-generated from `B_OccupancyToInstancesResult` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct OccupancyToInstancesResult {
    pub flora_instance_len: [u32; 5],
    pub has_growing_flora: u32,
}

/// Auto-generated from `B_PlayerCollisionResult` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct PlayerCollisionResult {
    pub ground_distance: f32,
    pub ceiling_distance: f32,
    pub ring_distances: [u32; 32],
}

/// Auto-generated from `B_RegionIndirect` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct RegionIndirect {
    pub dispatch_x: u32,
    pub dispatch_y: u32,
    pub dispatch_z: u32,
}

/// Auto-generated from `B_RoundCones` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct RoundCones {
    pub center_a: [f32; 3],
    pub radius_a: f32,
    pub center_b: [f32; 3],
    pub radius_b: f32,
}

/// Auto-generated from `B_SolidWorkgroupFlags` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct SolidWorkgroupFlags {
    pub data: [u32; 0],
}

/// Auto-generated from `B_Spheres` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct Spheres {
    pub center: [f32; 3],
    pub radius: f32,
}

/// Auto-generated from `B_SurfaceActiveBrickFlags` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct SurfaceActiveBrickFlags {
    pub data: [u32; 0],
}

/// Auto-generated from `B_SurfaceActiveBrickIndices` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct SurfaceActiveBrickIndices {
    pub data: [u32; 0],
}

/// Auto-generated from `B_TerrainQueryInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct TerrainQueryInfo {
    pub origin: [f32; 4],
    pub direction: [f32; 4],
}

/// Auto-generated from `B_TerrainQueryResult` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct TerrainQueryResult {
    pub hit_pos_and_valid: [u32; 0],
}

/// Auto-generated from `B_TreeLeafInstances` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct TreeLeafInstances {
    pub packed_local_pos: u32,
    pub packed_leaf_local_pos: u32,
}

/// Auto-generated from `B_VoxelPropertySampleResult` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct VoxelPropertySampleResult {
    pub stats: [u32; 4],
    pub extra: [u32; 4],
}

/// Auto-generated from `B_WindSources` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct WindSources {
    pub params: [f32; 4],
    pub noise: [f32; 4],
}

/// Auto-generated from `PushConstantChunkModifySample` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct PushConstantChunkModifySample {
    pub edit_seed: u32,
    pub _pad0: [u8; 12],
}

/// Auto-generated from `PushConstantFlora` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct PushConstantFlora {
    pub time: f32,
    pub instance_ty: u32,
    pub _pad0: [u8; 8],
    pub chunk_world_offset: [u32; 3],
    pub _padding_after_chunk_world_offset: u32,
    pub height_dark_color_rgb10: [u32; 12],
    pub height_light_color_rgb10: [u32; 12],
}

/// Auto-generated from `PushConstantFloraLod` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct PushConstantFloraLod {
    pub time: f32,
    pub instance_ty: u32,
    pub _pad0: [u8; 8],
    pub chunk_world_offset: [u32; 3],
    pub _padding_after_chunk_world_offset: u32,
    pub height_dark_color_rgb10: [u32; 12],
    pub height_light_color_rgb10: [u32; 12],
}

/// Auto-generated from `PushConstantLeafShadowTemporal` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct PushConstantLeafShadowTemporal {
    pub temporal_alpha: f32,
    pub reset_history: u32,
    pub _pad0: [u8; 8],
}

/// Auto-generated from `PushConstantLeavesShadow` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct PushConstantLeavesShadow {
    pub time: f32,
    pub instance_ty: u32,
    pub _pad0: [u8; 8],
    pub chunk_world_offset: [u32; 3],
    pub _padding_after_chunk_world_offset: u32,
    pub height_dark_color_rgb10: [u32; 12],
    pub height_light_color_rgb10: [u32; 12],
}

/// Auto-generated from `PushConstantSpatial` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct PushConstantSpatial {
    pub iteration: u32,
    pub _pad0: [u8; 12],
}

/// Auto-generated from `PushConstantVsmBlurH` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct PushConstantVsmBlurH {
    pub blur_radius: u32,
    pub temporal_alpha: f32,
    pub reset_history: u32,
    pub _pad0: [u8; 4],
}

/// Auto-generated from `PushConstantVsmBlurV` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct PushConstantVsmBlurV {
    pub blur_radius: u32,
    pub temporal_alpha: f32,
    pub reset_history: u32,
    pub _pad0: [u8; 4],
}

/// Auto-generated from `PushConstantWindVolume` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct PushConstantWindVolume {
    pub time: f32,
    pub bucket_index: u32,
    pub _pad0: [u8; 8],
}

/// Auto-generated from `U_CameraInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct CameraInfo {
    pub pos: [f32; 4],
    pub view_mat: [[f32; 4]; 4],
    pub view_mat_inv: [[f32; 4]; 4],
    pub proj_mat: [[f32; 4]; 4],
    pub proj_mat_inv: [[f32; 4]; 4],
    pub view_proj_mat: [[f32; 4]; 4],
    pub view_proj_mat_inv: [[f32; 4]; 4],
}

/// Auto-generated from `U_CameraInfoPrevFrame` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct CameraInfoPrevFrame {
    pub pos: [f32; 4],
    pub view_mat: [[f32; 4]; 4],
    pub view_mat_inv: [[f32; 4]; 4],
    pub proj_mat: [[f32; 4]; 4],
    pub proj_mat_inv: [[f32; 4]; 4],
    pub view_proj_mat: [[f32; 4]; 4],
    pub view_proj_mat_inv: [[f32; 4]; 4],
}

/// Auto-generated from `U_ChunkModifyInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct ChunkModifyInfo {
    pub offset: [u32; 3],
    pub _pad0: [u8; 4],
    pub dim: [u32; 3],
    pub fill_voxel_type: u32,
    pub target_voxel_type: u32,
    pub primitive_kind: u32,
    pub surface_only: u32,
    pub max_write_count: u32,
    pub max_removed_counts_0_3: [u32; 4],
    pub max_removed_counts_4_7: [u32; 4],
}

/// Auto-generated from `U_ChunkSolidSampleInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct ChunkSolidSampleInfo {
    pub atlas_offset: [u32; 3],
    pub _pad0: [u8; 4],
    pub atlas_dim: [u32; 3],
    pub _pad1: [u8; 4],
    pub sample_dim: [u32; 3],
    pub _pad2: [u8; 4],
}

/// Auto-generated from `U_ClearOccupancyInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct ClearOccupancyInfo {
    pub chunk_dim: [u32; 3],
    pub _pad0: [u8; 4],
}

/// Auto-generated from `U_ContreeBuildInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct ContreeBuildInfo {
    pub dim: u32,
    pub max_level: u32,
    pub node_write_offset: u32,
    pub leaf_write_offset: u32,
}

/// Auto-generated from `U_EditOccupancyInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct EditOccupancyInfo {
    pub edit_segment_start_radius_vox: [f32; 4],
    pub edit_segment_end_radius_vox: [f32; 4],
    pub chunk_world_offset: [u32; 3],
    pub _pad0: [u8; 4],
    pub chunk_dim: [u32; 3],
    pub mode: u32,
    pub flora_tick: u32,
    pub target_age: u32,
    pub paint_selection: u32,
    pub _pad1: [u8; 4],
    pub paint_config: [u32; 4],
}

/// Auto-generated from `U_EnvInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct EnvInfo {
    pub frame_serial_idx: u32,
    pub _pad0: [u8; 12],
}

/// Auto-generated from `U_FloraGrowthInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct FloraGrowthInfo {
    pub flora_tick: u32,
    pub sprout_delay_ticks: u32,
    pub full_growth_ticks: u32,
    pub spawn_time_ms: u32,
    pub spawn_duration_seconds: f32,
    pub spawn_rise_fraction: f32,
    pub spawn_overshoot_min_voxels: f32,
    pub spawn_overshoot_max_voxels: f32,
    pub spawn_stagger_seconds: f32,
    pub _pad0: [u8; 12],
    pub moisture_growth_factors: [u32; 20],
}

/// Auto-generated from `U_GodRayInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct GodRayInfo {
    pub max_depth: f32,
    pub max_checks: u32,
    pub weight: f32,
    pub _pad0: [u8; 4],
    pub color: [f32; 3],
    pub _pad1: [u8; 4],
}

/// Auto-generated from `U_GuiInput` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct GuiInput {
    pub debug_float: f32,
    pub debug_bool: u32,
    pub debug_uint: u32,
    pub flora_growth_override_enabled: u32,
    pub flora_growth_override: f32,
    pub terrain_shadow_use_vsm: u32,
    pub _pad0: [u8; 8],
    pub flora_instance_hsv_offset_max: [f32; 3],
    pub _pad1: [u8; 4],
    pub flora_voxel_hsv_offset_max: [f32; 3],
    pub _pad2: [u8; 4],
    pub grass_bottom_dark: [f32; 3],
    pub _pad3: [u8; 4],
    pub grass_bottom_light: [f32; 3],
    pub _pad4: [u8; 4],
    pub grass_tip_dark: [f32; 3],
    pub _pad5: [u8; 4],
    pub grass_tip_light: [f32; 3],
    pub _pad6: [u8; 4],
    pub glass_tint: [f32; 3],
    pub glass_reflection_strength: f32,
    pub glass_ssr_strength: f32,
    pub glass_ssr_steps: u32,
    pub glass_per_voxel_reflection: u32,
    pub glass_ssr_min_hit_thickness_voxels: f32,
    pub glass_ssr_footprint_pixels: f32,
    pub glass_refraction_strength: f32,
    pub glass_alpha: f32,
    pub glass_glint_strength: f32,
    pub lens_flare_intensity: f32,
    pub lens_flare_sun_pixel_scale: f32,
    pub wind_source_count: u32,
    pub wind_directional_bias_fraction: f32,
    pub wind_turbulence_fraction: f32,
    pub world_tick_seconds: f32,
    pub grass_vibration_amplitude_voxels: f32,
    pub grass_vibration_primary_speed: f32,
    pub grass_vibration_secondary_speed: f32,
    pub grass_natural_bend_min_voxels: f32,
    pub grass_natural_bend_max_voxels: f32,
    pub flora_bend_height_power: f32,
    pub kochia_body_wind_response: f32,
    pub kochia_branch_jelly_amplitude_voxels: f32,
    pub kochia_branch_jelly_speed: f32,
    pub kochia_branch_phase_spread: f32,
    pub kochia_tip_flutter_amplitude_voxels: f32,
    pub kochia_tip_flutter_speed: f32,
    pub leaf_paddle_amplitude_voxels: f32,
    pub leaf_paddle_primary_speed: f32,
    pub leaf_paddle_secondary_speed: f32,
    pub leaf_paddle_amplitude_wind_start_strength: f32,
    pub leaf_paddle_amplitude_wind_full_strength: f32,
    pub leaf_paddle_amplitude_wind_knee_bias: f32,
    pub leaf_paddle_frequency_wind_start_strength: f32,
    pub leaf_paddle_frequency_wind_full_strength: f32,
    pub leaf_paddle_frequency_wind_knee_bias: f32,
    pub leaf_paddle_frequency_min_multiplier: f32,
    pub leaf_paddle_frequency_max_multiplier: f32,
    pub fruit_swing_length_voxels: f32,
    pub fruit_swing_max_angle_radians: f32,
    pub fruit_swing_speed: f32,
    pub fruit_swing_speed_variation: f32,
    pub fruit_swing_min_response: f32,
    pub leaf_shadow_fragment_opacity: f32,
    pub leaf_shadow_strength: f32,
    pub leaf_shadow_min_transmittance: f32,
    pub leaf_shadow_filter_radius_texels: f32,
    pub clouds_enabled: u32,
    pub cloud_coverage: f32,
    pub cloud_density: f32,
    pub cloud_bottom_height: f32,
    pub cloud_top_height: f32,
    pub cloud_shape_scale: f32,
    pub cloud_detail_scale: f32,
    pub cloud_detail_strength: f32,
    pub cloud_wind_speed: f32,
    pub cloud_primary_steps: u32,
    pub cloud_light_steps: u32,
    pub cloud_temporal_alpha: f32,
    pub cloud_absorption: f32,
    pub cloud_phase_eccentricity: f32,
    pub cloud_silver_intensity: f32,
    pub cloud_max_distance: f32,
    pub cloud_shadows_enabled: u32,
    pub cloud_shadow_strength: f32,
    pub cloud_shadow_min_transmittance: f32,
    pub cloud_shadow_steps: u32,
    pub _pad7: [u8; 8],
}

/// Auto-generated from `U_InstancesToOccupancyInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct InstancesToOccupancyInfo {
    pub chunk_world_offset: [u32; 3],
    pub _pad0: [u8; 4],
    pub chunk_dim: [u32; 3],
    pub _pad1: [u8; 4],
    pub species_instance_len: [u32; 4],
    pub tick_delta: u32,
    pub spawn_time_ms: u32,
    pub _pad2: [u8; 8],
}

/// Auto-generated from `U_MakeSurfaceInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct MakeSurfaceInfo {
    pub atlas_read_offset: [u32; 3],
    pub _pad0: [u8; 4],
    pub atlas_read_dim: [u32; 3],
    pub is_crossing_boundary: u32,
}

/// Auto-generated from `U_ModelVoxelizeInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct ModelVoxelizeInfo {
    pub offset: [u32; 3],
    pub triangle_count: u32,
    pub dim: [u32; 3],
    pub fill_voxel_type: u32,
    pub position_vox: [f32; 3],
    pub surface_thickness_vox: f32,
}

/// Auto-generated from `U_OccupancyToInstancesInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct OccupancyToInstancesInfo {
    pub chunk_world_offset: [u32; 3],
    pub _pad0: [u8; 4],
    pub chunk_dim: [u32; 3],
    pub spawn_time_ms: u32,
    pub preserve_existing_placements: u32,
    pub _pad1: [u8; 12],
}

/// Auto-generated from `U_PlayerColliderInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct PlayerColliderInfo {
    pub player_pos: [f32; 3],
    pub _pad0: [u8; 4],
    pub camera_front: [f32; 3],
    pub _pad1: [u8; 4],
}

/// Auto-generated from `U_PostProcessingInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct PostProcessingInfo {
    pub scaling_factor: f32,
    pub _pad0: [u8; 12],
}

/// Auto-generated from `U_RegionInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct RegionInfo {
    pub offset: [u32; 3],
    pub _pad0: [u8; 4],
    pub dim: [u32; 3],
    pub _pad1: [u8; 4],
}

/// Auto-generated from `U_SceneTexUpdateInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct SceneTexUpdateInfo {
    pub chunk_idx: [u32; 3],
    pub node_offset_for_chunk: u32,
    pub leaf_offset_for_chunk: u32,
    pub is_valid: u32,
    pub _pad0: [u8; 8],
}

/// Auto-generated from `U_ShadingInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct ShadingInfo {
    pub ambient_light: [f32; 3],
    pub _pad0: [u8; 4],
}

/// Auto-generated from `U_ShadowCameraInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct ShadowCameraInfo {
    pub pos: [f32; 4],
    pub view_mat: [[f32; 4]; 4],
    pub view_mat_inv: [[f32; 4]; 4],
    pub proj_mat: [[f32; 4]; 4],
    pub proj_mat_inv: [[f32; 4]; 4],
    pub view_proj_mat: [[f32; 4]; 4],
    pub view_proj_mat_inv: [[f32; 4]; 4],
}

/// Auto-generated from `U_SpatialInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct SpatialInfo {
    pub phi_c: f32,
    pub phi_n: f32,
    pub phi_p: f32,
    pub min_phi_z: f32,
    pub max_phi_z: f32,
    pub phi_z_stable_sample_count: f32,
    pub is_changing_lum_phi: u32,
    pub is_spatial_denoising_enabled: u32,
}

/// Auto-generated from `U_StarlightInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct StarlightInfo {
    pub iterations: i32,
    pub formuparam: f32,
    pub volsteps: i32,
    pub stepsize: f32,
    pub zoom: f32,
    pub tile: f32,
    pub speed: f32,
    pub brightness: f32,
    pub darkmatter: f32,
    pub distfading: f32,
    pub saturation: f32,
    pub _pad0: [u8; 4],
}

/// Auto-generated from `U_SunInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct SunInfo {
    pub sun_dir: [f32; 3],
    pub sun_size: f32,
    pub sun_color: [f32; 3],
    pub sun_luminance: f32,
    pub sun_display_luminance: f32,
    pub sun_altitude: f32,
    pub sun_azimuth: f32,
    pub _pad0: [u8; 4],
}

/// Auto-generated from `U_TemporalInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct TemporalInfo {
    pub temporal_position_phi: f32,
    pub temporal_alpha: f32,
    pub _pad0: [u8; 8],
}

/// Auto-generated from `U_TerrainEditPreview` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct TerrainEditPreview {
    pub center: [f32; 3],
    pub radius: f32,
    pub color: [f32; 3],
    pub strength: f32,
    pub enabled: u32,
    pub shape: u32,
    pub _pad0: [u8; 8],
}

/// Auto-generated from `U_TerrainQueryCount` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct TerrainQueryCount {
    pub valid_query_count: u32,
    pub _pad0: [u8; 12],
}

/// Auto-generated from `U_VoxelColors` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct VoxelColors {
    pub dirt_color: [f32; 3],
    pub _pad0: [u8; 4],
    pub sand_color: [f32; 3],
    pub _pad1: [u8; 4],
    pub cherry_wood_color: [f32; 3],
    pub _pad2: [u8; 4],
    pub oak_wood_color: [f32; 3],
    pub _pad3: [u8; 4],
    pub rock_color: [f32; 3],
    pub hash_color_variance: f32,
}

/// Auto-generated from `U_VoxelPropertySampleInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct VoxelPropertySampleInfo {
    pub atlas_offset_property_id: [u32; 4],
    pub atlas_dim_target_mask: [u32; 4],
    pub center_radius: [f32; 4],
    pub options: [u32; 4],
}

/// Auto-generated from `U_WindVolumeInfo` (GLSL source of truth).
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct WindVolumeInfo {
    pub world_chunk_extent: [f32; 3],
    pub _pad0: [u8; 4],
}
