#version 460

#extension GL_GOOGLE_include_directive : require

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

#include "../include/gui_input.glsl"
layout(set = 0, binding = 1) uniform U_SunInfo {
    vec3 sun_dir;
    float sun_size;
    vec3 sun_color;
    float sun_luminance;
    float sun_display_luminance;
    float sun_altitude;
    float sun_azimuth;
}
sun_info;
layout(set = 0, binding = 4) uniform U_CameraInfo {
    vec4 pos;
    mat4 view_mat;
    mat4 view_mat_inv;
    mat4 proj_mat;
    mat4 proj_mat_inv;
    mat4 view_proj_mat;
    mat4 view_proj_mat_inv;
}
camera_info;
layout(set = 0, binding = 5) uniform U_EnvInfo { uint frame_serial_idx; }
env_info;
layout(set = 0, binding = 15, rgba16f) uniform writeonly image2D cloud_output_tex;

#include "../include/core/transform.glsl"
#include "../include/ray.glsl"
#include "../include/skylight.glsl"
#include "../include/sunlight.glsl"
#include "../include/clouds.glsl"

void main() {
    ivec2 uvi = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(cloud_output_tex);
    if (any(greaterThanEqual(uvi, size))) {
        return;
    }

    vec2 screen_uv = (vec2(uvi) + vec2(0.5)) / vec2(size);
    Ray ray = ray_gen(screen_uv, camera_info.view_proj_mat_inv);

    CloudRaymarchResult clouds = compute_volumetric_clouds(ray.direction, 0u);
    imageStore(cloud_output_tex, uvi, vec4(clouds.color, clouds.alpha));
}
