#version 460

#extension GL_GOOGLE_include_directive : require

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform U_GuiInput {
    float debug_float;
    uint debug_bool;
    uint debug_uint;
    vec3 flora_instance_hsv_offset_max;
    vec3 flora_voxel_hsv_offset_max;
    vec3 grass_bottom_dark;
    vec3 grass_bottom_light;
    vec3 grass_tip_dark;
    vec3 grass_tip_light;
    vec3 ocean_deep_color;
    vec3 ocean_shallow_color;
    float ocean_normal_amplitude;
    float ocean_noise_frequency;
    float ocean_time_multiplier;
    float ocean_sea_level_shift;
    float lens_flare_intensity;
    float lens_flare_sun_pixel_scale;
}
gui_input;
layout(set = 0, binding = 1) uniform U_PostProcessingInfo { float scaling_factor; }
post_processing_info;
layout(set = 0, binding = 2, r11f_g11f_b10f) uniform readonly image2D composited_tex;
layout(set = 0, binding = 3, rgba8) uniform writeonly image2D screen_output_tex;

#include "../include/core/dither.glsl"

void main() {
    ivec2 uvi = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(uvi, imageSize(screen_output_tex)))) {
        return;
    }

    vec2 scaling_factor = vec2(imageSize(composited_tex)) / vec2(imageSize(screen_output_tex));
    ivec2 mapped_uvi    = ivec2(vec2(uvi) * scaling_factor);
    vec3 final_color    = imageLoad(composited_tex, mapped_uvi).rgb;

    vec3 dither_mask = get_dither_mask(uvi);
    final_color += dither_mask * 3.0;

    imageStore(screen_output_tex, uvi, vec4(final_color, 1.0));
}
