#version 460

#extension GL_GOOGLE_include_directive : require

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform U_TerrainQueryCount { uint valid_query_count; }
terrain_query_count;

struct TerrainRayQuery {
    vec4 origin;
    vec4 direction;
};

layout(set = 0, binding = 1) readonly buffer B_TerrainQueryInfo { TerrainRayQuery data[]; }
terrain_query_info;

#include "../include/contree_node.glsl"

layout(set = 0, binding = 2) readonly buffer B_ContreeNodeData { ContreeNode data[]; }
contree_node_data;

layout(set = 0, binding = 3) readonly buffer B_ContreeLeafData { uint data[]; }
contree_leaf_data;

layout(set = 0, binding = 4, rg32ui) readonly uniform uimage3D scene_tex;

layout(set = 0, binding = 5) writeonly buffer B_TerrainQueryResult { vec4 hit_pos_and_valid[]; }
terrain_query_result;

#include "../include/contree_marching.glsl"
#include "../include/core/packer.glsl"
#include "../include/marching_result.glsl"
#include "../include/ray.glsl"
#include "../include/voxel_data.glsl"

bool scene_hit(inout MarchingResult o_res, vec3 o, vec3 d, ivec3 map_pos, uvec4 scene_tex_read) {
    if (scene_tex_read.x == 0) {
        return false;
    }
    scene_tex_read -= 1;

    ContreeMarchingResult contree_res =
        contree_marching(o, d, map_pos, vec3(1.0), false, scene_tex_read.x, scene_tex_read.y);
    if (contree_res.is_hit) {
        uint voxel_data       = contree_leaf_data.data[contree_res.voxel_addr];
        o_res.is_hit          = true;
        o_res.pos             = contree_res.pos;
        o_res.center_pos      = contree_res.center_pos;
        o_res.is_normal_valid = true;
        o_res.normal          = voxel_surface_normal_from_data(voxel_data);
        o_res.voxel_type      = voxel_type_from_data(voxel_data);
        o_res.hash_id         = voxel_hash_from_data(voxel_data);
        o_res.voxel_addr      = contree_res.voxel_addr;
        return true;
    }
    return false;
}
#include "../include/dda_scene_marching.glsl"

MarchingResult general_scene_marching(Ray ray) {
    return dda_scene_marching(ray.origin, ray.direction, ray.inv_direction);
}

void main() {
    uint query_index = gl_GlobalInvocationID.x;

    if (query_index >= terrain_query_count.valid_query_count) {
        return;
    }

    vec3 ray_origin = terrain_query_info.data[query_index].origin.xyz;
    vec3 ray_dir    = terrain_query_info.data[query_index].direction.xyz;
    if (dot(ray_dir, ray_dir) < 1e-8) {
        terrain_query_result.hit_pos_and_valid[query_index] = vec4(0.0, 0.0, 0.0, 0.0);
        return;
    }
    ray_dir = normalize(ray_dir);

    Ray ray;
    ray.origin        = ray_origin;
    ray.direction     = ray_dir;
    ray.inv_direction = 1.0 / ray.direction;

    MarchingResult res = general_scene_marching(ray);

    if (res.is_hit) {
        terrain_query_result.hit_pos_and_valid[query_index] = vec4(res.pos, 1.0);
    } else {
        terrain_query_result.hit_pos_and_valid[query_index] = vec4(0.0, 0.0, 0.0, 0.0);
    }
}
