//! The purpose of this file is to define the configuration for the shader compiler to optimize.
//! This file may be generated by rust code later.
#ifndef CONFIG_GLSL
#define CONFIG_GLSL

#define VOXEL_DIM 256

#endif // CONFIG_GLSL
