#ifndef TRANSFORM_GLSL
#define TRANSFORM_GLSL

/// Constructs a TBN matrix, given that world up is y-axis
/// TBN is orthonormal basis, so transpose is the same as inverse
/// This is used to transform a vector from tangent space to world space
/// The tangent and bitangent generated by this function are not so useful because lack of
/// information
/// They should be passed by raster pipelines as attributes
/// So this function is useful only when the normal distribution is uniformly distributed
/// Usage: TBN * <tangent_space_vector> = <world_space_vector>
/// Usage: transpose(TBN) * <world_space_vector> = <tangent_space_vector>
mat3 make_tbn(vec3 normal) {
    vec3 up, t;
    if (abs(normal.y) < 0.99999) {
        up = vec3(0, 1, 0);
        t  = normalize(cross(up, normal));
    } else {
        up = vec3(1, 0, 0);
        t  = normalize(cross(normal, up));
    }
    vec3 b = cross(normal, t);
    return mat3(t, b, normal);
}

#endif // TRANSFORM_GLSL
