use shaderc::{CompileOptions, Compiler, EnvVersion, OptimizationLevel, ShaderKind, SpirvVersion};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const ENTRY_POINT: &str = "main";

fn main() {
    let crate_root = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let project_root = crate_root
        .parent()
        .and_then(Path::parent)
        .expect("re-flora-vkn must live under <project>/crates/re-flora-vkn");
    let shader_root = project_root.join("shader");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    println!("cargo:rerun-if-changed={}", shader_root.display());

    let mut shader_paths = Vec::new();
    collect_shader_paths(&shader_root, &mut shader_paths);
    shader_paths.sort();

    let compiler = Compiler::new().expect("create shader compiler");
    let artifact_root = out_dir.join("precompiled-shaders");
    let mut generated = String::from(
        "// Generated by crates/re-flora-vkn/build.rs. Do not edit.\n\
         pub(crate) struct PrecompiledShader {\n\
         \tpub(crate) reflection_spirv: &'static [u8],\n\
         \tpub(crate) optimized_spirv: &'static [u8],\n\
         }\n\n\
         pub(crate) fn find_precompiled_shader(file_path: &str) -> Option<PrecompiledShader> {\n\
         \tmatch file_path {\n",
    );

    for shader_path in &shader_paths {
        let relative_path = shader_path
            .strip_prefix(project_root)
            .expect("shader path must be under project root");
        let logical_path = path_with_forward_slashes(relative_path);
        let shader_kind = shader_kind(shader_path);
        let source = fs::read_to_string(shader_path)
            .unwrap_or_else(|error| panic!("read {}: {error}", shader_path.display()));

        let reflection_spirv = compile_shader(
            &compiler,
            &source,
            shader_kind,
            shader_path,
            OptimizationLevel::Zero,
        );
        let optimized_spirv = compile_shader(
            &compiler,
            &source,
            shader_kind,
            shader_path,
            OptimizationLevel::Performance,
        );

        let artifact_path = artifact_root.join(relative_path);
        let reflection_path = append_extension(&artifact_path, "reflection.spv");
        let optimized_path = append_extension(&artifact_path, "optimized.spv");
        fs::create_dir_all(
            reflection_path
                .parent()
                .expect("shader artifact must have parent"),
        )
        .expect("create shader artifact directory");
        fs::write(&reflection_path, reflection_spirv)
            .unwrap_or_else(|error| panic!("write {}: {error}", reflection_path.display()));
        fs::write(&optimized_path, optimized_spirv)
            .unwrap_or_else(|error| panic!("write {}: {error}", optimized_path.display()));

        let relative_reflection = path_with_forward_slashes(
            reflection_path
                .strip_prefix(&out_dir)
                .expect("artifact must be under OUT_DIR"),
        );
        let relative_optimized = path_with_forward_slashes(
            optimized_path
                .strip_prefix(&out_dir)
                .expect("artifact must be under OUT_DIR"),
        );
        generated.push_str(&format!(
            "\t\t{logical_path:?} => Some(PrecompiledShader {{\n\
             \t\t\treflection_spirv: include_bytes!(concat!(env!(\"OUT_DIR\"), {reflection:?})),\n\
             \t\t\toptimized_spirv: include_bytes!(concat!(env!(\"OUT_DIR\"), {optimized:?})),\n\
             \t\t}}),\n",
            reflection = format!("/{relative_reflection}"),
            optimized = format!("/{relative_optimized}"),
        ));
    }

    generated.push_str("\t\t_ => None,\n\t}\n}\n");
    fs::write(out_dir.join("precompiled_shaders.rs"), generated)
        .expect("write generated precompiled shader registry");

    println!(
        "cargo:warning=precompiled {} GLSL shaders into SPIR-V artifacts",
        shader_paths.len()
    );
}

fn collect_shader_paths(directory: &Path, shader_paths: &mut Vec<PathBuf>) {
    let entries = fs::read_dir(directory)
        .unwrap_or_else(|error| panic!("read shader directory {}: {error}", directory.display()));
    for entry in entries {
        let path = entry.expect("read shader directory entry").path();
        if path.is_dir() {
            collect_shader_paths(&path, shader_paths);
        } else if matches!(
            path.extension().and_then(|extension| extension.to_str()),
            Some("comp" | "vert" | "frag")
        ) {
            shader_paths.push(path);
        }
    }
}

fn shader_kind(path: &Path) -> ShaderKind {
    match path.extension().and_then(|extension| extension.to_str()) {
        Some("comp") => ShaderKind::Compute,
        Some("vert") => ShaderKind::Vertex,
        Some("frag") => ShaderKind::Fragment,
        extension => panic!("unsupported shader extension {extension:?}: {}", path.display()),
    }
}

fn compile_shader(
    compiler: &Compiler,
    source: &str,
    shader_kind: ShaderKind,
    shader_path: &Path,
    optimization_level: OptimizationLevel,
) -> Vec<u8> {
    let mut options = CompileOptions::new().expect("create shader compile options");
    options.set_target_env(shaderc::TargetEnv::Vulkan, EnvVersion::Vulkan1_3 as u32);
    options.set_target_spirv(SpirvVersion::V1_6);
    options.set_source_language(shaderc::SourceLanguage::GLSL);
    options.set_optimization_level(optimization_level);
    options.set_include_callback(resolve_include);

    compiler
        .compile_into_spirv(
            source,
            shader_kind,
            shader_path.to_string_lossy().as_ref(),
            ENTRY_POINT,
            Some(&options),
        )
        .unwrap_or_else(|error| {
            panic!(
                "compile {} with {optimization_level:?}: {error}",
                shader_path.display()
            )
        })
        .as_binary_u8()
        .to_vec()
}

fn resolve_include(
    requested_source: &str,
    include_type: shaderc::IncludeType,
    requesting_source: &str,
    _include_depth: usize,
) -> Result<shaderc::ResolvedInclude, String> {
    let base_dir = match include_type {
        shaderc::IncludeType::Relative => Path::new(requesting_source)
            .parent()
            .ok_or_else(|| format!("{requesting_source} has no parent directory"))?,
        shaderc::IncludeType::Standard => {
            return Err("standard shader includes are not supported".to_owned())
        }
    };
    let full_path = base_dir
        .join(requested_source)
        .canonicalize()
        .map_err(|error| format!("resolve {requested_source}: {error}"))?;
    let content = fs::read_to_string(&full_path)
        .map_err(|error| format!("read {}: {error}", full_path.display()))?;

    Ok(shaderc::ResolvedInclude {
        resolved_name: full_path.to_string_lossy().into_owned(),
        content,
    })
}

fn append_extension(path: &Path, extension: &str) -> PathBuf {
    let mut result = path.as_os_str().to_owned();
    result.push(".");
    result.push(extension);
    result.into()
}

fn path_with_forward_slashes(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}
