use shaderc::{CompileOptions, Compiler, EnvVersion, OptimizationLevel, ShaderKind, SpirvVersion};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

const ENTRY_POINT: &str = "main";

#[allow(dead_code)]
#[derive(Clone, Copy)]
enum SlangSourceLanguage {
    Slang2025,
    Glsl,
}

#[derive(Clone, Copy)]
struct SlangShaderConfig {
    logical_path: &'static str,
    source_path: &'static str,
    include_path: &'static str,
    stage: &'static str,
    source_language: SlangSourceLanguage,
    defines: &'static [&'static str],
}

const SLANG_SHADER_CONFIGS: &[SlangShaderConfig] = &[
    #[cfg(feature = "slang-contree-leaf")]
    SlangShaderConfig {
        logical_path: "shader/builder/contree/leaf_write.comp",
        source_path: "shader/experiments/slang/contree_leaf_write.slang",
        include_path: "shader/experiments/slang",
        stage: "compute",
        source_language: SlangSourceLanguage::Slang2025,
        defines: &[],
    },
    #[cfg(feature = "slang-post-processing")]
    SlangShaderConfig {
        logical_path: "shader/tracer/post_processing.comp",
        source_path: "shader/experiments/slang/post_processing.slang",
        include_path: "shader/experiments/slang",
        stage: "compute",
        source_language: SlangSourceLanguage::Slang2025,
        defines: &[],
    },
    #[cfg(feature = "slang-surface")]
    SlangShaderConfig {
        logical_path: "shader/builder/surface/make_surface_sparse.comp",
        source_path: "shader/experiments/slang/make_surface_sparse.slang",
        include_path: "shader/experiments/slang",
        stage: "compute",
        source_language: SlangSourceLanguage::Slang2025,
        defines: &[],
    },
    #[cfg(feature = "slang-tracer-backend")]
    SlangShaderConfig {
        logical_path: "shader/tracer/tracer.comp",
        source_path: "shader/tracer/tracer.comp",
        include_path: "shader",
        stage: "compute",
        source_language: SlangSourceLanguage::Glsl,
        defines: &["DIRECT_SUN_SHADOW_EXPLICIT_LOD"],
    },
];

fn main() {
    let crate_root = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let project_root = crate_root
        .parent()
        .and_then(Path::parent)
        .expect("re-flora-vkn must live under <project>/crates/re-flora-vkn");
    let shader_root = project_root.join("shader");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    println!("cargo:rerun-if-changed={}", shader_root.display());
    println!("cargo:rerun-if-env-changed=SLANGC");
    println!("cargo:rerun-if-env-changed=VULKAN_SDK");

    let mut shader_paths = Vec::new();
    collect_shader_paths(&shader_root, &mut shader_paths);
    shader_paths.sort();

    let compiler = Compiler::new().expect("create shader compiler");
    let artifact_root = out_dir.join("precompiled-shaders");
    let mut generated = String::from(
        "// Generated by crates/re-flora-vkn/build.rs. Do not edit.\n\
         pub(crate) struct PrecompiledShader {\n\
         \tpub(crate) reflection_spirv: &'static [u8],\n\
         \tpub(crate) optimized_spirv: &'static [u8],\n\
         }\n\n\
         pub(crate) fn find_precompiled_shader(file_path: &str) -> Option<PrecompiledShader> {\n\
         \tmatch file_path {\n",
    );

    let mut slang_shader_count = 0;
    for shader_path in &shader_paths {
        let relative_path = shader_path
            .strip_prefix(project_root)
            .expect("shader path must be under project root");
        let logical_path = path_with_forward_slashes(relative_path);
        let slang_config = SLANG_SHADER_CONFIGS
            .iter()
            .find(|config| config.logical_path == logical_path);

        let (reflection_spirv, optimized_spirv) = if let Some(config) = slang_config {
            slang_shader_count += 1;
            (
                compile_slang_shader(
                    config,
                    project_root,
                    &out_dir,
                    OptimizationLevel::Zero,
                ),
                compile_slang_shader(
                    config,
                    project_root,
                    &out_dir,
                    OptimizationLevel::Performance,
                ),
            )
        } else {
            let source = fs::read_to_string(shader_path)
                .unwrap_or_else(|error| panic!("read {}: {error}", shader_path.display()));
            let shader_kind = shader_kind(shader_path);
            (
                compile_shader(
                    &compiler,
                    &source,
                    shader_kind,
                    shader_path,
                    OptimizationLevel::Zero,
                ),
                compile_shader(
                    &compiler,
                    &source,
                    shader_kind,
                    shader_path,
                    OptimizationLevel::Performance,
                ),
            )
        };

        let artifact_path = artifact_root.join(relative_path);
        let reflection_path = append_extension(&artifact_path, "reflection.spv");
        let optimized_path = append_extension(&artifact_path, "optimized.spv");
        fs::create_dir_all(
            reflection_path
                .parent()
                .expect("shader artifact must have parent"),
        )
        .expect("create shader artifact directory");
        fs::write(&reflection_path, reflection_spirv)
            .unwrap_or_else(|error| panic!("write {}: {error}", reflection_path.display()));
        fs::write(&optimized_path, optimized_spirv)
            .unwrap_or_else(|error| panic!("write {}: {error}", optimized_path.display()));

        let relative_reflection = path_with_forward_slashes(
            reflection_path
                .strip_prefix(&out_dir)
                .expect("artifact must be under OUT_DIR"),
        );
        let relative_optimized = path_with_forward_slashes(
            optimized_path
                .strip_prefix(&out_dir)
                .expect("artifact must be under OUT_DIR"),
        );
        generated.push_str(&format!(
            "\t\t{logical_path:?} => Some(PrecompiledShader {{\n\
             \t\t\treflection_spirv: include_bytes!(concat!(env!(\"OUT_DIR\"), {reflection:?})),\n\
             \t\t\toptimized_spirv: include_bytes!(concat!(env!(\"OUT_DIR\"), {optimized:?})),\n\
             \t\t}}),\n",
            reflection = format!("/{relative_reflection}"),
            optimized = format!("/{relative_optimized}"),
        ));
    }

    generated.push_str("\t\t_ => None,\n\t}\n}\n");
    fs::write(out_dir.join("precompiled_shaders.rs"), generated)
        .expect("write generated precompiled shader registry");

    println!(
        "cargo:warning=precompiled {} GLSL shaders and {} Slang shaders into SPIR-V artifacts",
        shader_paths.len() - slang_shader_count,
        slang_shader_count,
    );
}

fn compile_slang_shader(
    config: &SlangShaderConfig,
    project_root: &Path,
    out_dir: &Path,
    optimization_level: OptimizationLevel,
) -> Vec<u8> {
    let (optimization_arg, artifact_suffix) = match optimization_level {
        OptimizationLevel::Zero => ("-O0", "reflection"),
        OptimizationLevel::Performance => ("-O3", "optimized"),
        other => panic!("unsupported Slang optimization level: {other:?}"),
    };
    let artifact_stem: String = config
        .logical_path
        .chars()
        .map(|character| match character {
            '/' | '\\' | '.' => '-',
            other => other,
        })
        .collect();
    let output_path = out_dir
        .join("slang")
        .join(format!("{artifact_stem}-{artifact_suffix}.spv"));
    fs::create_dir_all(output_path.parent().expect("Slang artifact must have parent"))
        .expect("create Slang artifact directory");

    let shader_path = project_root.join(config.source_path);
    let include_path = project_root.join(config.include_path);
    let slangc = find_slangc();
    // Slang's GLSL frontend lowers column-major GLSL matrices through row-major
    // storage wrappers. Selecting row-major here preserves GLSL's std140 byte
    // interpretation; native Slang sources use the project's column-major mode.
    let matrix_layout_arg = match config.source_language {
        SlangSourceLanguage::Slang2025 => "-matrix-layout-column-major",
        SlangSourceLanguage::Glsl => "-matrix-layout-row-major",
    };

    let mut command = Command::new(&slangc);
    command.args([
        shader_path.as_os_str(),
        "-I".as_ref(),
        include_path.as_os_str(),
        "-target".as_ref(),
        "spirv".as_ref(),
        "-profile".as_ref(),
        "spirv_1_6".as_ref(),
        "-entry".as_ref(),
        ENTRY_POINT.as_ref(),
        "-stage".as_ref(),
        config.stage.as_ref(),
        matrix_layout_arg.as_ref(),
        "-fvk-use-gl-layout".as_ref(),
        optimization_arg.as_ref(),
    ]);
    match config.source_language {
        SlangSourceLanguage::Slang2025 => {
            command.args(["-std", "2025"]);
        }
        SlangSourceLanguage::Glsl => {
            command.arg("-allow-glsl");
        }
    }
    for define in config.defines {
        command.arg(format!("-D{define}"));
    }
    if optimization_level == OptimizationLevel::Zero {
        command.arg("-preserve-params");
    }
    command.arg("-o").arg(&output_path);

    let output = command.output().unwrap_or_else(|error| {
        panic!(
            "run Slang compiler {} for {}: {error}. Install slangc from the Vulkan SDK or set SLANGC",
            slangc.display(),
            shader_path.display(),
        )
    });
    if !output.status.success() {
        panic!(
            "compile {} with Slang {optimization_arg}:\n{}{}",
            shader_path.display(),
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr),
        );
    }

    fs::read(&output_path).unwrap_or_else(|error| panic!("read {}: {error}", output_path.display()))
}

fn find_slangc() -> PathBuf {
    if let Some(path) = env::var_os("SLANGC") {
        return PathBuf::from(path);
    }
    if let Some(vulkan_sdk) = env::var_os("VULKAN_SDK") {
        let candidate = PathBuf::from(vulkan_sdk)
            .join("bin")
            .join(format!("slangc{}", env::consts::EXE_SUFFIX));
        if candidate.is_file() {
            return candidate;
        }
    }
    PathBuf::from(format!("slangc{}", env::consts::EXE_SUFFIX))
}

fn collect_shader_paths(directory: &Path, shader_paths: &mut Vec<PathBuf>) {
    let entries = fs::read_dir(directory)
        .unwrap_or_else(|error| panic!("read shader directory {}: {error}", directory.display()));
    for entry in entries {
        let path = entry.expect("read shader directory entry").path();
        if path.is_dir() {
            collect_shader_paths(&path, shader_paths);
        } else if matches!(
            path.extension().and_then(|extension| extension.to_str()),
            Some("comp" | "vert" | "frag")
        ) {
            shader_paths.push(path);
        }
    }
}

fn shader_kind(path: &Path) -> ShaderKind {
    match path.extension().and_then(|extension| extension.to_str()) {
        Some("comp") => ShaderKind::Compute,
        Some("vert") => ShaderKind::Vertex,
        Some("frag") => ShaderKind::Fragment,
        extension => panic!("unsupported shader extension {extension:?}: {}", path.display()),
    }
}

fn compile_shader(
    compiler: &Compiler,
    source: &str,
    shader_kind: ShaderKind,
    shader_path: &Path,
    optimization_level: OptimizationLevel,
) -> Vec<u8> {
    let mut options = CompileOptions::new().expect("create shader compile options");
    options.set_target_env(shaderc::TargetEnv::Vulkan, EnvVersion::Vulkan1_3 as u32);
    options.set_target_spirv(SpirvVersion::V1_6);
    options.set_source_language(shaderc::SourceLanguage::GLSL);
    options.set_optimization_level(optimization_level);
    options.set_include_callback(resolve_include);

    compiler
        .compile_into_spirv(
            source,
            shader_kind,
            shader_path.to_string_lossy().as_ref(),
            ENTRY_POINT,
            Some(&options),
        )
        .unwrap_or_else(|error| {
            panic!(
                "compile {} with {optimization_level:?}: {error}",
                shader_path.display()
            )
        })
        .as_binary_u8()
        .to_vec()
}

fn resolve_include(
    requested_source: &str,
    include_type: shaderc::IncludeType,
    requesting_source: &str,
    _include_depth: usize,
) -> Result<shaderc::ResolvedInclude, String> {
    let base_dir = match include_type {
        shaderc::IncludeType::Relative => Path::new(requesting_source)
            .parent()
            .ok_or_else(|| format!("{requesting_source} has no parent directory"))?,
        shaderc::IncludeType::Standard => {
            return Err("standard shader includes are not supported".to_owned())
        }
    };
    let full_path = base_dir
        .join(requested_source)
        .canonicalize()
        .map_err(|error| format!("resolve {requested_source}: {error}"))?;
    let content = fs::read_to_string(&full_path)
        .map_err(|error| format!("read {}: {error}", full_path.display()))?;

    Ok(shaderc::ResolvedInclude {
        resolved_name: full_path.to_string_lossy().into_owned(),
        content,
    })
}

fn append_extension(path: &Path, extension: &str) -> PathBuf {
    let mut result = path.as_os_str().to_owned();
    result.push(".");
    result.push(extension);
    result.into()
}

fn path_with_forward_slashes(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}
