use re_flora_shader_build::{
    NativeSlangCompiler, OptimizationLevel, ShaderConfig, ShaderStage, NATIVE_SHADERS,
};
use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const ARTIFACT_CACHE_VERSION: &str = "shader-artifact-cache-v2-native-slang";

fn main() {
    let crate_root = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let project_root = crate_root
        .parent()
        .and_then(Path::parent)
        .expect("re-flora-vkn must live under <project>/crates/re-flora-vkn");
    let shader_root = project_root.join("shader/slang");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    println!("cargo:rerun-if-changed={}", shader_root.display());
    println!("cargo:rerun-if-env-changed=SLANGC");
    println!("cargo:rerun-if-env-changed=SLANG_LIB");
    println!("cargo:rerun-if-env-changed=VULKAN_SDK");

    validate_native_shaders(project_root);
    let compiler = NativeSlangCompiler::new();
    let common_cache_dependencies = [
        crate_root.join("build.rs"),
        crate_root.join("Cargo.toml"),
        project_root.join("crates/re-flora-shader-build/src/lib.rs"),
        project_root.join("crates/re-flora-shader-build/Cargo.toml"),
        project_root.join("Cargo.lock"),
    ]
    .into_iter()
    .map(|path| canonical_dependency(&path))
    .collect::<BTreeSet<_>>();
    let artifact_root = out_dir.join("precompiled-shaders");
    let mut generated = String::from(
        "// Generated by crates/re-flora-vkn/build.rs. Do not edit.\n\
         pub(crate) struct PrecompiledShader {\n\
         \tpub(crate) reflection_spirv: &'static [u8],\n\
         \tpub(crate) optimized_spirv: &'static [u8],\n\
         }\n\n\
         pub(crate) fn find_precompiled_shader(file_path: &str) -> Option<PrecompiledShader> {\n\
         \tmatch file_path {\n",
    );

    let mut compiled_shader_count = 0;
    let mut reused_shader_count = 0;
    for shader in NATIVE_SHADERS {
        let logical_path = shader.logical_path;
        let relative_path = Path::new(logical_path);
        let artifact_path = artifact_root.join(relative_path);
        let reflection_path = append_extension(&artifact_path, "reflection.spv");
        let optimized_path = append_extension(&artifact_path, "optimized.spv");
        let cache_path = append_extension(&artifact_path, "cache");
        fs::create_dir_all(
            reflection_path
                .parent()
                .expect("shader artifact must have a parent"),
        )
        .expect("create shader artifact directory");

        let cache_context = shader_cache_context(shader, compiler.build_tag());
        if artifact_cache_is_current(
            &cache_path,
            &reflection_path,
            &optimized_path,
            &cache_context,
        ) {
            reused_shader_count += 1;
        } else {
            remove_cache_marker(&cache_path);
            let reflection =
                compiler.compile_shader(shader, project_root, OptimizationLevel::Zero);
            let optimized =
                compiler.compile_shader(shader, project_root, OptimizationLevel::Performance);
            let mut dependencies = reflection.dependencies;
            dependencies.extend(optimized.dependencies);
            dependencies.extend(common_cache_dependencies.iter().cloned());

            fs::write(&reflection_path, reflection.spirv)
                .unwrap_or_else(|error| panic!("write {}: {error}", reflection_path.display()));
            fs::write(&optimized_path, optimized.spirv)
                .unwrap_or_else(|error| panic!("write {}: {error}", optimized_path.display()));
            write_artifact_cache(
                &cache_path,
                &reflection_path,
                &optimized_path,
                &cache_context,
                &dependencies,
            );
            compiled_shader_count += 1;
        }

        let relative_reflection = path_with_forward_slashes(
            reflection_path
                .strip_prefix(&out_dir)
                .expect("artifact must be under OUT_DIR"),
        );
        let relative_optimized = path_with_forward_slashes(
            optimized_path
                .strip_prefix(&out_dir)
                .expect("artifact must be under OUT_DIR"),
        );
        generated.push_str(&format!(
            "\t\t{logical_path:?} => Some(PrecompiledShader {{\n\
             \t\t\treflection_spirv: include_bytes!(concat!(env!(\"OUT_DIR\"), {reflection:?})),\n\
             \t\t\toptimized_spirv: include_bytes!(concat!(env!(\"OUT_DIR\"), {optimized:?})),\n\
             \t\t}}),\n",
            reflection = format!("/{relative_reflection}"),
            optimized = format!("/{relative_optimized}"),
        ));
    }

    generated.push_str("\t\t_ => None,\n\t}\n}\n");
    write_if_changed(&out_dir.join("precompiled_shaders.rs"), generated.as_bytes());

    println!(
        "cargo:warning=precompiled {} native Slang shaders into SPIR-V artifacts (compiled {}, reused {})",
        NATIVE_SHADERS.len(),
        compiled_shader_count,
        reused_shader_count,
    );
}

// Cache entries use dependency paths reported by Slang after a successful
// compile. On later build-script runs, content and artifact digests
// let unrelated shader changes reuse both reflection and optimized SPIR-V.
fn shader_cache_context(shader: &ShaderConfig, slang_build_tag: &str) -> String {
    let mut hasher = blake3::Hasher::new();
    hash_field(&mut hasher, ARTIFACT_CACHE_VERSION.as_bytes());
    hash_field(&mut hasher, shader.logical_path.as_bytes());
    hash_field(&mut hasher, shader.source_path.as_bytes());
    hash_field(&mut hasher, shader.module_path.as_bytes());
    hash_field(
        &mut hasher,
        match shader.stage {
            ShaderStage::Compute => b"compute",
            ShaderStage::Vertex => b"vertex",
            ShaderStage::Fragment => b"fragment",
        },
    );
    hash_field(&mut hasher, b"native-slang-2025");
    hash_field(&mut hasher, slang_build_tag.as_bytes());
    hash_field(
        &mut hasher,
        env::var("TARGET")
            .expect("TARGET must be available to build scripts")
            .as_bytes(),
    );
    hasher.finalize().to_hex().to_string()
}

fn artifact_cache_is_current(
    cache_path: &Path,
    reflection_path: &Path,
    optimized_path: &Path,
    cache_context: &str,
) -> bool {
    let Ok(manifest) = fs::read_to_string(cache_path) else {
        return false;
    };
    let mut lines = manifest.lines();
    if lines.next() != Some(ARTIFACT_CACHE_VERSION) {
        return false;
    }
    if lines
        .next()
        .and_then(|line| line.strip_prefix("context="))
        != Some(cache_context)
    {
        return false;
    }
    let Some(expected_dependency_digest) = lines
        .next()
        .and_then(|line| line.strip_prefix("dependencies="))
    else {
        return false;
    };
    let Some(expected_reflection_digest) = lines
        .next()
        .and_then(|line| line.strip_prefix("reflection="))
    else {
        return false;
    };
    let Some(expected_optimized_digest) = lines
        .next()
        .and_then(|line| line.strip_prefix("optimized="))
    else {
        return false;
    };
    let mut dependencies = BTreeSet::new();
    for line in lines {
        let Some(path) = line.strip_prefix("dependency=") else {
            return false;
        };
        dependencies.insert(PathBuf::from(path));
    }
    if dependencies.is_empty() {
        return false;
    }

    dependency_digest(&dependencies).as_deref() == Some(expected_dependency_digest)
        && file_digest(reflection_path).as_deref() == Some(expected_reflection_digest)
        && file_digest(optimized_path).as_deref() == Some(expected_optimized_digest)
}

fn write_artifact_cache(
    cache_path: &Path,
    reflection_path: &Path,
    optimized_path: &Path,
    cache_context: &str,
    dependencies: &BTreeSet<PathBuf>,
) {
    let dependency_digest = dependency_digest(dependencies)
        .unwrap_or_else(|| panic!("hash dependencies for {}", cache_path.display()));
    let reflection_digest = file_digest(reflection_path)
        .unwrap_or_else(|| panic!("hash {}", reflection_path.display()));
    let optimized_digest = file_digest(optimized_path)
        .unwrap_or_else(|| panic!("hash {}", optimized_path.display()));
    let mut manifest = format!(
        "{ARTIFACT_CACHE_VERSION}\ncontext={cache_context}\ndependencies={dependency_digest}\nreflection={reflection_digest}\noptimized={optimized_digest}\n"
    );
    for dependency in dependencies {
        let dependency = path_with_forward_slashes(dependency);
        assert!(
            !dependency.contains(['\n', '\r']),
            "shader dependency path contains a newline: {dependency:?}",
        );
        manifest.push_str("dependency=");
        manifest.push_str(&dependency);
        manifest.push('\n');
    }
    write_if_changed(cache_path, manifest.as_bytes());
}

fn dependency_digest(dependencies: &BTreeSet<PathBuf>) -> Option<String> {
    let mut hasher = blake3::Hasher::new();
    for dependency in dependencies {
        let dependency = fs::canonicalize(dependency).ok()?;
        let contents = fs::read(&dependency).ok()?;
        hash_field(
            &mut hasher,
            path_with_forward_slashes(&dependency).as_bytes(),
        );
        hash_field(&mut hasher, &contents);
    }
    Some(hasher.finalize().to_hex().to_string())
}

fn file_digest(path: &Path) -> Option<String> {
    fs::read(path)
        .ok()
        .map(|contents| blake3::hash(&contents).to_hex().to_string())
}

fn hash_field(hasher: &mut blake3::Hasher, value: &[u8]) {
    hasher.update(&(value.len() as u64).to_le_bytes());
    hasher.update(value);
}

fn canonical_dependency(path: &Path) -> PathBuf {
    fs::canonicalize(path)
        .unwrap_or_else(|error| panic!("resolve shader dependency {}: {error}", path.display()))
}

fn remove_cache_marker(path: &Path) {
    if let Err(error) = fs::remove_file(path) {
        assert_eq!(
            error.kind(),
            std::io::ErrorKind::NotFound,
            "remove stale shader cache marker {}: {error}",
            path.display(),
        );
    }
}

fn write_if_changed(path: &Path, contents: &[u8]) {
    if fs::read(path).is_ok_and(|existing| existing == contents) {
        return;
    }
    fs::write(path, contents).unwrap_or_else(|error| panic!("write {}: {error}", path.display()));
}

fn validate_native_shaders(project_root: &Path) {
    let mut logical_paths = BTreeSet::new();
    let mut source_paths = BTreeSet::new();
    for shader in NATIVE_SHADERS {
        assert!(
            logical_paths.insert(shader.logical_path),
            "duplicate native shader logical path: {}",
            shader.logical_path,
        );
        assert!(
            source_paths.insert(shader.source_path),
            "duplicate native shader entry source: {}",
            shader.source_path,
        );
        assert_eq!(
            Path::new(shader.logical_path)
                .extension()
                .and_then(|extension| extension.to_str()),
            Some(shader.stage.file_extension()),
            "native shader stage does not match logical path: {}",
            shader.logical_path,
        );
        let source_path = project_root.join(shader.source_path);
        assert_eq!(
            source_path.extension().and_then(|extension| extension.to_str()),
            Some("slang"),
            "native shader source must use .slang: {}",
            source_path.display(),
        );
        assert!(source_path.is_file(), "missing native shader: {}", source_path.display());
        assert!(
            project_root.join(shader.module_path).is_dir(),
            "missing native shader include directory: {}",
            shader.module_path,
        );
    }
}

fn append_extension(path: &Path, extension: &str) -> PathBuf {
    let mut result = path.as_os_str().to_owned();
    result.push(".");
    result.push(extension);
    result.into()
}

fn path_with_forward_slashes(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}
