[package]
name = "re-flora-vkn"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.102"
ash = { version = "0.38", default-features = false, features = [
    "debug",
    "loaded",
    "std",
] }
ash-window = "0.13"
bytemuck = "1.25.0"
comfy-table = "7.2.2"
glam = { version = "0.32.1", features = ["debug-glam-assert", "bytemuck"] }
gpu-allocator = "0.28.0"
image = "0.25.10"
log = "0.4.29"
spirv-reflect = { git = "https://github.com/gwihlidal/spirv-reflect-rs.git", rev = "97298067e3b1c9ce05633d78f1183c14a3cc6acc" }
winit = { version = "0.30", features = ["rwh_05"] }

[build-dependencies]
blake3 = "1"
libloading = "0.8"
shaderc = { version = "0.10.1", features = ["prefer-static-linking"] }
spirv-reflect = { git = "https://github.com/gwihlidal/spirv-reflect-rs.git", rev = "97298067e3b1c9ce05633d78f1183c14a3cc6acc" }

[features]
default = []
no_validation_layer = []
slang-composition = []
slang-composition-backend = []
slang-contree = [
    "slang-contree-buffer-setup",
    "slang-contree-buffer-update",
    "slang-contree-concat",
    "slang-contree-last-buffer-update",
    "slang-contree-leaf",
    "slang-contree-tree-write",
]
slang-contree-buffer-setup = []
slang-contree-buffer-update = []
slang-contree-concat = []
slang-contree-last-buffer-update = []
slang-contree-leaf = []
slang-contree-tree-write = []
slang-denoiser = ["slang-denoiser-spatial", "slang-denoiser-temporal"]
slang-denoiser-spatial = []
slang-denoiser-temporal = []
slang-egui = []
slang-flora = []
slang-player-collider = []
slang-poc = ["slang-post-processing"]
slang-post-processing = []
slang-scene-accel = []
slang-surface = [
    "slang-surface-active-to-flora-instances",
    "slang-surface-clear-occupancy",
    "slang-surface-edit-occupancy-capsule",
    "slang-surface-instances-to-occupancy",
    "slang-surface-make",
    "slang-surface-make-sparse",
    "slang-surface-occupancy-to-flora-instances",
    "slang-surface-prepare-active-flora-dispatch",
    "slang-surface-prepare-sparse-dispatch",
    "slang-surface-update-flora-growth",
]
slang-surface-active-to-flora-instances = []
slang-surface-clear-occupancy = []
slang-surface-edit-occupancy-capsule = []
slang-surface-instances-to-occupancy = []
slang-surface-make = []
slang-surface-make-sparse = []
slang-surface-occupancy-to-flora-instances = []
slang-surface-prepare-active-flora-dispatch = []
slang-surface-prepare-sparse-dispatch = []
slang-surface-update-flora-growth = []
slang-tracer = []
slang-tracer-backend = []
slang-tracer-shadow = []
slang-tracer-shadow-depth-copy = []
slang-tracer-vsm = [
    "slang-tracer-shadow-depth-copy",
    "slang-tracer-vsm-blur-h",
    "slang-tracer-vsm-blur-v",
    "slang-tracer-vsm-creation",
]
slang-tracer-vsm-blur-h = []
slang-tracer-vsm-blur-v = []
slang-tracer-vsm-creation = []
slang-validation = [
    "slang-composition",
    "slang-contree",
    "slang-denoiser",
    "slang-egui",
    "slang-flora",
    "slang-player-collider",
    "slang-post-processing",
    "slang-scene-accel",
    "slang-surface",
    "slang-tracer",
    "slang-tracer-shadow",
    "slang-tracer-vsm",
]
sync_diagnostics = []
