#version 450
#extension GL_GOOGLE_include_directive : require

layout(local_size_x = 50, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform PC {
    uint edit_seed;
}
pc;

layout(set = 0, binding = 6) readonly buffer B_EditStats {
    uint removed_counts[8];
    uint added_counts[8];
}
edit_stats;
layout(set = 0, binding = 7) readonly buffer B_EditRemovalCandidates { vec4 positions[]; }
edit_removal_candidates;
layout(set = 0, binding = 8) buffer B_EditRemovalSample {
    uint sample_count;
    vec4 positions[50];
}
edit_removal_sample;

#include "../../include/core/hash.glsl"
#include "../../include/voxel_types.glsl"

const uint EDIT_REMOVAL_SAMPLE_COUNT = 50u;

void main() {
    uint sample_idx    = gl_GlobalInvocationID.x;
    uint candidate_len = edit_stats.added_counts[VOXEL_TYPE_EMPTY];
    uint sample_count  = min(candidate_len, EDIT_REMOVAL_SAMPLE_COUNT);

    if (sample_idx == 0u) {
        edit_removal_sample.sample_count = sample_count;
    }

    if (sample_idx >= EDIT_REMOVAL_SAMPLE_COUNT) {
        return;
    }

    if (sample_idx >= sample_count) {
        edit_removal_sample.positions[sample_idx] = vec4(0.0);
        return;
    }

    uint candidate_idx = murmurhash_12(uvec2(pc.edit_seed, sample_idx)) % candidate_len;
    edit_removal_sample.positions[sample_idx] = edit_removal_candidates.positions[candidate_idx];
}
